[package]
name = "rust_decimal"
version = "0.10.1"
authors = ["Paul Mason <paul@form1.co.nz>"]

description = "A Decimal Implementation written in pure Rust suitable for financial calculations."
documentation = "https://docs.rs/rust_decimal/"
repository = "https://github.com/paupino/rust-decimal"
readme = "./README.md"

keywords = ["decimal","financial","fixed","precision"]
categories = ["science","data-structures"]

license = "MIT"

[badges]
travis-ci = { repository = "paupino/rust-decimal", branch = "master" }

[dependencies]
num = "0.2"
byteorder = "1.2"
lazy_static = "1.1"
postgres = { version = "0.15", optional = true }
serde = { version = "1.0", optional = true }

[dev-dependencies]
decimal = "2.0"
rand = "0.5"
serde_json = "1.0"
serde_derive = "1.0"

[features]
default = ["serde"]
comparitive = []
fuzz = []

[workspace]
members = [".", "./macros"]